#define SPI_IO_MAGIC    'G'


#define CMD_SPI_START _IO(SPI_IO_MAGIC,0x80)
#define CMD_SPI_STOP _IO(SPI_IO_MAGIC,0x81)
#define CMD_SPI_FREQUENCY _IOW(SPI_IO_MAGIC,0x82,int)
#define CMD_SPI_BUS_SPEED _IOW(SPI_IO_MAGIC,0x83,int)
#define CMD_SPI_BITS_PER_WORD _IOW(SPI_IO_MAGIC,0x84,int)
#define CMD_SPI_NB_ECH        _IOW(SPI_IO_MAGIC,0x85,int)
#define CMD_TEST        _IOW(SPI_IO_MAGIC,0x86,int) 
