#############################################################################
#
#	Makefile for building MyDriver kernel module
#
#############################################################################

#ifneq ($(KERNELRELEASE),)
# call from kernel build system

obj-m := ifsttar-synchronization-drv.o

#else

APP_IOCTL_TEST_DIR = ifsttar-synchronization-ioctl-test-app
APP_FCT_TEST_DIR = ifsttar-synchronization-fct-test-app
DRIVER_TEST_DIR = ifsttar-synchronization-test-drv

PWD       		= $(shell pwd)

#CROSS_COMPILE	?= arm-angstrom-linux-gnueabi-
#KERNEL_PATH 	?= $(OECORE_TARGET_SYSROOT)/usr/src/linux
# modif pour yocto
KERNEL_PATH 	?= $(OECORE_TARGET_SYSROOT)/usr/src/kernel
ARCH			?= arm
#CC=arm-angstrom-linux-gnueabi-gcc
#LD=arm-angstrom-linux-gnueabi-ld
#STRIP=arm-angstrom-linux-gnueabi-strip
MACHINE=overo

#export ARCH CROSS_COMPILE CC LD STRIP


export-objs     := ifsttar-synchronzation-drv.o

KBUILD_FLAGS	= -C $(KERNEL_PATH) M=$(PWD)

driver:
	$(MAKE) $(KBUILD_FLAGS) modules

all : driver
	$(MAKE) -C $(DRIVER_TEST_DIR) all
	$(MAKE) -C $(APP_IOCTL_TEST_DIR) all
	$(MAKE) -C $(APP_FCT_TEST_DIR) all
	
clear: 
	clear ; make clean

clean:
	rm -rf *.o .*.o.d *~ *.ko *.mod.c .*.cmd .tmp* *.order *.symvers *.markers
	$(MAKE) -C $(DRIVER_TEST_DIR) clean
	$(MAKE) -C $(APP_IOCTL_TEST_DIR) clean
	$(MAKE) -C $(APP_FCT_TEST_DIR) clean

#endif
